//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Estudiante", Namespace="http://schemas.datacontract.org/2004/07/TecnologiasProyect.Model")]
    public partial class Estudiante : object
    {
        
        private ServiceReference1.Academico AcademicoField;
        
        private int IdEstudianteField;
        
        private int IdProgramaEducativoField;
        
        private int IdTutorField;
        
        private ServiceReference1.ProblematicaPersonal[] ProblematicaPersonalField;
        
        private ServiceReference1.ProgramaEducativo ProgramaEducativoField;
        
        private ServiceReference1.ReporteTutoria[] ReporteTutoriaField;
        
        private string apellidoMaternoField;
        
        private string apellidoPaternoField;
        
        private string correoInstitucionalField;
        
        private string correoPersonalField;
        
        private string matriculaField;
        
        private string nombreField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.Academico Academico
        {
            get
            {
                return this.AcademicoField;
            }
            set
            {
                this.AcademicoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdEstudiante
        {
            get
            {
                return this.IdEstudianteField;
            }
            set
            {
                this.IdEstudianteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdProgramaEducativo
        {
            get
            {
                return this.IdProgramaEducativoField;
            }
            set
            {
                this.IdProgramaEducativoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTutor
        {
            get
            {
                return this.IdTutorField;
            }
            set
            {
                this.IdTutorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.ProblematicaPersonal[] ProblematicaPersonal
        {
            get
            {
                return this.ProblematicaPersonalField;
            }
            set
            {
                this.ProblematicaPersonalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.ProgramaEducativo ProgramaEducativo
        {
            get
            {
                return this.ProgramaEducativoField;
            }
            set
            {
                this.ProgramaEducativoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.ReporteTutoria[] ReporteTutoria
        {
            get
            {
                return this.ReporteTutoriaField;
            }
            set
            {
                this.ReporteTutoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string apellidoMaterno
        {
            get
            {
                return this.apellidoMaternoField;
            }
            set
            {
                this.apellidoMaternoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string apellidoPaterno
        {
            get
            {
                return this.apellidoPaternoField;
            }
            set
            {
                this.apellidoPaternoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string correoInstitucional
        {
            get
            {
                return this.correoInstitucionalField;
            }
            set
            {
                this.correoInstitucionalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string correoPersonal
        {
            get
            {
                return this.correoPersonalField;
            }
            set
            {
                this.correoPersonalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string matricula
        {
            get
            {
                return this.matriculaField;
            }
            set
            {
                this.matriculaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Academico", Namespace="http://schemas.datacontract.org/2004/07/TecnologiasProyect.Model")]
    public partial class Academico : object
    {
        
        private ServiceReference1.Estudiante[] EstudianteField;
        
        private ServiceReference1.ExperienciaEducativa[] ExperienciaEducativaField;
        
        private int IdAcademicoField;
        
        private ServiceReference1.ProgramaEducativo[] ProgramaEducativoField;
        
        private ServiceReference1.ProgramaEducativo[] ProgramaEducativo1Field;
        
        private ServiceReference1.ProgramaEducativoTutor[] ProgramaEducativoTutorField;
        
        private ServiceReference1.ReporteTutoria[] ReporteTutoriaField;
        
        private string apellidoMaternoField;
        
        private string apellidoPaternoField;
        
        private string correoInstitucionalField;
        
        private string correoPersonalField;
        
        private string noPersonalField;
        
        private string nombreField;
        
        private string passwordField;
        
        private string rolField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.Estudiante[] Estudiante
        {
            get
            {
                return this.EstudianteField;
            }
            set
            {
                this.EstudianteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.ExperienciaEducativa[] ExperienciaEducativa
        {
            get
            {
                return this.ExperienciaEducativaField;
            }
            set
            {
                this.ExperienciaEducativaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdAcademico
        {
            get
            {
                return this.IdAcademicoField;
            }
            set
            {
                this.IdAcademicoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.ProgramaEducativo[] ProgramaEducativo
        {
            get
            {
                return this.ProgramaEducativoField;
            }
            set
            {
                this.ProgramaEducativoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.ProgramaEducativo[] ProgramaEducativo1
        {
            get
            {
                return this.ProgramaEducativo1Field;
            }
            set
            {
                this.ProgramaEducativo1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.ProgramaEducativoTutor[] ProgramaEducativoTutor
        {
            get
            {
                return this.ProgramaEducativoTutorField;
            }
            set
            {
                this.ProgramaEducativoTutorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.ReporteTutoria[] ReporteTutoria
        {
            get
            {
                return this.ReporteTutoriaField;
            }
            set
            {
                this.ReporteTutoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string apellidoMaterno
        {
            get
            {
                return this.apellidoMaternoField;
            }
            set
            {
                this.apellidoMaternoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string apellidoPaterno
        {
            get
            {
                return this.apellidoPaternoField;
            }
            set
            {
                this.apellidoPaternoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string correoInstitucional
        {
            get
            {
                return this.correoInstitucionalField;
            }
            set
            {
                this.correoInstitucionalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string correoPersonal
        {
            get
            {
                return this.correoPersonalField;
            }
            set
            {
                this.correoPersonalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string noPersonal
        {
            get
            {
                return this.noPersonalField;
            }
            set
            {
                this.noPersonalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string rol
        {
            get
            {
                return this.rolField;
            }
            set
            {
                this.rolField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProgramaEducativo", Namespace="http://schemas.datacontract.org/2004/07/TecnologiasProyect.Model")]
    public partial class ProgramaEducativo : object
    {
        
        private ServiceReference1.Academico AcademicoField;
        
        private ServiceReference1.Academico Academico1Field;
        
        private ServiceReference1.Estudiante[] EstudianteField;
        
        private ServiceReference1.ExperienciaEducativa[] ExperienciaEducativaField;
        
        private int IdAcademicoJefeField;
        
        private int IdCoordinadorField;
        
        private int IdProgramaEducativoField;
        
        private ServiceReference1.ProgramaEducativoTutor[] ProgramaEducativoTutorField;
        
        private ServiceReference1.ReporteTutoria[] ReporteTutoriaField;
        
        private ServiceReference1.Solucion[] SolucionField;
        
        private string areaField;
        
        private string modalidadField;
        
        private string nombreField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.Academico Academico
        {
            get
            {
                return this.AcademicoField;
            }
            set
            {
                this.AcademicoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.Academico Academico1
        {
            get
            {
                return this.Academico1Field;
            }
            set
            {
                this.Academico1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.Estudiante[] Estudiante
        {
            get
            {
                return this.EstudianteField;
            }
            set
            {
                this.EstudianteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.ExperienciaEducativa[] ExperienciaEducativa
        {
            get
            {
                return this.ExperienciaEducativaField;
            }
            set
            {
                this.ExperienciaEducativaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdAcademicoJefe
        {
            get
            {
                return this.IdAcademicoJefeField;
            }
            set
            {
                this.IdAcademicoJefeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCoordinador
        {
            get
            {
                return this.IdCoordinadorField;
            }
            set
            {
                this.IdCoordinadorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdProgramaEducativo
        {
            get
            {
                return this.IdProgramaEducativoField;
            }
            set
            {
                this.IdProgramaEducativoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.ProgramaEducativoTutor[] ProgramaEducativoTutor
        {
            get
            {
                return this.ProgramaEducativoTutorField;
            }
            set
            {
                this.ProgramaEducativoTutorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.ReporteTutoria[] ReporteTutoria
        {
            get
            {
                return this.ReporteTutoriaField;
            }
            set
            {
                this.ReporteTutoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.Solucion[] Solucion
        {
            get
            {
                return this.SolucionField;
            }
            set
            {
                this.SolucionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string area
        {
            get
            {
                return this.areaField;
            }
            set
            {
                this.areaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string modalidad
        {
            get
            {
                return this.modalidadField;
            }
            set
            {
                this.modalidadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProblematicaPersonal", Namespace="http://schemas.datacontract.org/2004/07/TecnologiasProyect.Model")]
    public partial class ProblematicaPersonal : object
    {
        
        private ServiceReference1.Estudiante EstudianteField;
        
        private int IdEstudianteField;
        
        private int IdProblematicaField;
        
        private int IdProblematicaPersonalField;
        
        private ServiceReference1.Problematica ProblematicaField;
        
        private string descripcionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.Estudiante Estudiante
        {
            get
            {
                return this.EstudianteField;
            }
            set
            {
                this.EstudianteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdEstudiante
        {
            get
            {
                return this.IdEstudianteField;
            }
            set
            {
                this.IdEstudianteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdProblematica
        {
            get
            {
                return this.IdProblematicaField;
            }
            set
            {
                this.IdProblematicaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdProblematicaPersonal
        {
            get
            {
                return this.IdProblematicaPersonalField;
            }
            set
            {
                this.IdProblematicaPersonalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.Problematica Problematica
        {
            get
            {
                return this.ProblematicaField;
            }
            set
            {
                this.ProblematicaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descripcion
        {
            get
            {
                return this.descripcionField;
            }
            set
            {
                this.descripcionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReporteTutoria", Namespace="http://schemas.datacontract.org/2004/07/TecnologiasProyect.Model")]
    public partial class ReporteTutoria : object
    {
        
        private ServiceReference1.Academico AcademicoField;
        
        private ServiceReference1.ComentarioGeneral[] ComentarioGeneralField;
        
        private ServiceReference1.Estudiante EstudianteField;
        
        private int IdEstudianteField;
        
        private int IdProgramaEducativoField;
        
        private int IdReporteField;
        
        private int IdTutorField;
        
        private int IdTutoriaField;
        
        private ServiceReference1.Problematica[] ProblematicaField;
        
        private ServiceReference1.ProgramaEducativo ProgramaEducativoField;
        
        private ServiceReference1.Tutoria TutoriaField;
        
        private bool asistenciaField;
        
        private string descripcionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.Academico Academico
        {
            get
            {
                return this.AcademicoField;
            }
            set
            {
                this.AcademicoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.ComentarioGeneral[] ComentarioGeneral
        {
            get
            {
                return this.ComentarioGeneralField;
            }
            set
            {
                this.ComentarioGeneralField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.Estudiante Estudiante
        {
            get
            {
                return this.EstudianteField;
            }
            set
            {
                this.EstudianteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdEstudiante
        {
            get
            {
                return this.IdEstudianteField;
            }
            set
            {
                this.IdEstudianteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdProgramaEducativo
        {
            get
            {
                return this.IdProgramaEducativoField;
            }
            set
            {
                this.IdProgramaEducativoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdReporte
        {
            get
            {
                return this.IdReporteField;
            }
            set
            {
                this.IdReporteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTutor
        {
            get
            {
                return this.IdTutorField;
            }
            set
            {
                this.IdTutorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTutoria
        {
            get
            {
                return this.IdTutoriaField;
            }
            set
            {
                this.IdTutoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.Problematica[] Problematica
        {
            get
            {
                return this.ProblematicaField;
            }
            set
            {
                this.ProblematicaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.ProgramaEducativo ProgramaEducativo
        {
            get
            {
                return this.ProgramaEducativoField;
            }
            set
            {
                this.ProgramaEducativoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.Tutoria Tutoria
        {
            get
            {
                return this.TutoriaField;
            }
            set
            {
                this.TutoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool asistencia
        {
            get
            {
                return this.asistenciaField;
            }
            set
            {
                this.asistenciaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descripcion
        {
            get
            {
                return this.descripcionField;
            }
            set
            {
                this.descripcionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExperienciaEducativa", Namespace="http://schemas.datacontract.org/2004/07/TecnologiasProyect.Model")]
    public partial class ExperienciaEducativa : object
    {
        
        private ServiceReference1.Academico AcademicoField;
        
        private int IdAcademicoField;
        
        private int IdExperienciaEducativaField;
        
        private int IdMateriaField;
        
        private int IdPeriodoEscolarField;
        
        private int IdProgramaEducativoField;
        
        private ServiceReference1.Materia MateriaField;
        
        private ServiceReference1.PeriodoEscolar PeriodoEscolarField;
        
        private ServiceReference1.Problematica[] ProblematicaField;
        
        private ServiceReference1.ProgramaEducativo ProgramaEducativoField;
        
        private string bloqueField;
        
        private string nrcField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.Academico Academico
        {
            get
            {
                return this.AcademicoField;
            }
            set
            {
                this.AcademicoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdAcademico
        {
            get
            {
                return this.IdAcademicoField;
            }
            set
            {
                this.IdAcademicoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdExperienciaEducativa
        {
            get
            {
                return this.IdExperienciaEducativaField;
            }
            set
            {
                this.IdExperienciaEducativaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdMateria
        {
            get
            {
                return this.IdMateriaField;
            }
            set
            {
                this.IdMateriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPeriodoEscolar
        {
            get
            {
                return this.IdPeriodoEscolarField;
            }
            set
            {
                this.IdPeriodoEscolarField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdProgramaEducativo
        {
            get
            {
                return this.IdProgramaEducativoField;
            }
            set
            {
                this.IdProgramaEducativoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.Materia Materia
        {
            get
            {
                return this.MateriaField;
            }
            set
            {
                this.MateriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.PeriodoEscolar PeriodoEscolar
        {
            get
            {
                return this.PeriodoEscolarField;
            }
            set
            {
                this.PeriodoEscolarField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.Problematica[] Problematica
        {
            get
            {
                return this.ProblematicaField;
            }
            set
            {
                this.ProblematicaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.ProgramaEducativo ProgramaEducativo
        {
            get
            {
                return this.ProgramaEducativoField;
            }
            set
            {
                this.ProgramaEducativoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string bloque
        {
            get
            {
                return this.bloqueField;
            }
            set
            {
                this.bloqueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nrc
        {
            get
            {
                return this.nrcField;
            }
            set
            {
                this.nrcField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProgramaEducativoTutor", Namespace="http://schemas.datacontract.org/2004/07/TecnologiasProyect.Model")]
    public partial class ProgramaEducativoTutor : object
    {
        
        private ServiceReference1.Academico AcademicoField;
        
        private int IdAcademicoField;
        
        private int IdProgramaEducativoField;
        
        private int IdProgramaEducativoTutorField;
        
        private ServiceReference1.ProgramaEducativo ProgramaEducativoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.Academico Academico
        {
            get
            {
                return this.AcademicoField;
            }
            set
            {
                this.AcademicoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdAcademico
        {
            get
            {
                return this.IdAcademicoField;
            }
            set
            {
                this.IdAcademicoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdProgramaEducativo
        {
            get
            {
                return this.IdProgramaEducativoField;
            }
            set
            {
                this.IdProgramaEducativoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdProgramaEducativoTutor
        {
            get
            {
                return this.IdProgramaEducativoTutorField;
            }
            set
            {
                this.IdProgramaEducativoTutorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.ProgramaEducativo ProgramaEducativo
        {
            get
            {
                return this.ProgramaEducativoField;
            }
            set
            {
                this.ProgramaEducativoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Materia", Namespace="http://schemas.datacontract.org/2004/07/TecnologiasProyect.Model")]
    public partial class Materia : object
    {
        
        private ServiceReference1.ExperienciaEducativa[] ExperienciaEducativaField;
        
        private int IdMateriaField;
        
        private int creditosField;
        
        private string nombreField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.ExperienciaEducativa[] ExperienciaEducativa
        {
            get
            {
                return this.ExperienciaEducativaField;
            }
            set
            {
                this.ExperienciaEducativaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdMateria
        {
            get
            {
                return this.IdMateriaField;
            }
            set
            {
                this.IdMateriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int creditos
        {
            get
            {
                return this.creditosField;
            }
            set
            {
                this.creditosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PeriodoEscolar", Namespace="http://schemas.datacontract.org/2004/07/TecnologiasProyect.Model")]
    public partial class PeriodoEscolar : object
    {
        
        private ServiceReference1.ExperienciaEducativa[] ExperienciaEducativaField;
        
        private int IdPeriodoEscolarField;
        
        private System.DateTime fechaFinField;
        
        private System.DateTime fechaInicioField;
        
        private string nombreField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.ExperienciaEducativa[] ExperienciaEducativa
        {
            get
            {
                return this.ExperienciaEducativaField;
            }
            set
            {
                this.ExperienciaEducativaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPeriodoEscolar
        {
            get
            {
                return this.IdPeriodoEscolarField;
            }
            set
            {
                this.IdPeriodoEscolarField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fechaFin
        {
            get
            {
                return this.fechaFinField;
            }
            set
            {
                this.fechaFinField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fechaInicio
        {
            get
            {
                return this.fechaInicioField;
            }
            set
            {
                this.fechaInicioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Problematica", Namespace="http://schemas.datacontract.org/2004/07/TecnologiasProyect.Model")]
    public partial class Problematica : object
    {
        
        private ServiceReference1.ExperienciaEducativa ExperienciaEducativaField;
        
        private int IdExperienciaEducativaField;
        
        private int IdProblematicaField;
        
        private int IdReporteField;
        
        private int IdTipoField;
        
        private ServiceReference1.ProblematicaPersonal[] ProblematicaPersonalField;
        
        private ServiceReference1.ReporteTutoria ReporteTutoriaField;
        
        private ServiceReference1.Solucion[] SolucionField;
        
        private ServiceReference1.TipoProblematica TipoProblematicaField;
        
        private string descripcionField;
        
        private int noIncidenciasField;
        
        private string tituloField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.ExperienciaEducativa ExperienciaEducativa
        {
            get
            {
                return this.ExperienciaEducativaField;
            }
            set
            {
                this.ExperienciaEducativaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdExperienciaEducativa
        {
            get
            {
                return this.IdExperienciaEducativaField;
            }
            set
            {
                this.IdExperienciaEducativaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdProblematica
        {
            get
            {
                return this.IdProblematicaField;
            }
            set
            {
                this.IdProblematicaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdReporte
        {
            get
            {
                return this.IdReporteField;
            }
            set
            {
                this.IdReporteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTipo
        {
            get
            {
                return this.IdTipoField;
            }
            set
            {
                this.IdTipoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.ProblematicaPersonal[] ProblematicaPersonal
        {
            get
            {
                return this.ProblematicaPersonalField;
            }
            set
            {
                this.ProblematicaPersonalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.ReporteTutoria ReporteTutoria
        {
            get
            {
                return this.ReporteTutoriaField;
            }
            set
            {
                this.ReporteTutoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.Solucion[] Solucion
        {
            get
            {
                return this.SolucionField;
            }
            set
            {
                this.SolucionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.TipoProblematica TipoProblematica
        {
            get
            {
                return this.TipoProblematicaField;
            }
            set
            {
                this.TipoProblematicaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descripcion
        {
            get
            {
                return this.descripcionField;
            }
            set
            {
                this.descripcionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int noIncidencias
        {
            get
            {
                return this.noIncidenciasField;
            }
            set
            {
                this.noIncidenciasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string titulo
        {
            get
            {
                return this.tituloField;
            }
            set
            {
                this.tituloField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoProblematica", Namespace="http://schemas.datacontract.org/2004/07/TecnologiasProyect.Model")]
    public partial class TipoProblematica : object
    {
        
        private int IdTipoField;
        
        private ServiceReference1.Problematica[] ProblematicaField;
        
        private string tipoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTipo
        {
            get
            {
                return this.IdTipoField;
            }
            set
            {
                this.IdTipoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.Problematica[] Problematica
        {
            get
            {
                return this.ProblematicaField;
            }
            set
            {
                this.ProblematicaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tipo
        {
            get
            {
                return this.tipoField;
            }
            set
            {
                this.tipoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Solucion", Namespace="http://schemas.datacontract.org/2004/07/TecnologiasProyect.Model")]
    public partial class Solucion : object
    {
        
        private int IdProblematicaField;
        
        private int IdProgramaEducativoField;
        
        private int IdSolucionField;
        
        private ServiceReference1.Problematica ProblematicaField;
        
        private ServiceReference1.ProgramaEducativo ProgramaEducativoField;
        
        private string descripcionField;
        
        private string tituloField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdProblematica
        {
            get
            {
                return this.IdProblematicaField;
            }
            set
            {
                this.IdProblematicaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdProgramaEducativo
        {
            get
            {
                return this.IdProgramaEducativoField;
            }
            set
            {
                this.IdProgramaEducativoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdSolucion
        {
            get
            {
                return this.IdSolucionField;
            }
            set
            {
                this.IdSolucionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.Problematica Problematica
        {
            get
            {
                return this.ProblematicaField;
            }
            set
            {
                this.ProblematicaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.ProgramaEducativo ProgramaEducativo
        {
            get
            {
                return this.ProgramaEducativoField;
            }
            set
            {
                this.ProgramaEducativoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descripcion
        {
            get
            {
                return this.descripcionField;
            }
            set
            {
                this.descripcionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string titulo
        {
            get
            {
                return this.tituloField;
            }
            set
            {
                this.tituloField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Tutoria", Namespace="http://schemas.datacontract.org/2004/07/TecnologiasProyect.Model")]
    public partial class Tutoria : object
    {
        
        private int IdPeriodoEscolarField;
        
        private int IdTutoriaField;
        
        private ServiceReference1.ReporteTutoria[] ReporteTutoriaField;
        
        private System.DateTime fechaEntregaField;
        
        private System.DateTime fechaSesionField;
        
        private string noSesionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPeriodoEscolar
        {
            get
            {
                return this.IdPeriodoEscolarField;
            }
            set
            {
                this.IdPeriodoEscolarField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTutoria
        {
            get
            {
                return this.IdTutoriaField;
            }
            set
            {
                this.IdTutoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.ReporteTutoria[] ReporteTutoria
        {
            get
            {
                return this.ReporteTutoriaField;
            }
            set
            {
                this.ReporteTutoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fechaEntrega
        {
            get
            {
                return this.fechaEntregaField;
            }
            set
            {
                this.fechaEntregaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fechaSesion
        {
            get
            {
                return this.fechaSesionField;
            }
            set
            {
                this.fechaSesionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string noSesion
        {
            get
            {
                return this.noSesionField;
            }
            set
            {
                this.noSesionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ComentarioGeneral", Namespace="http://schemas.datacontract.org/2004/07/TecnologiasProyect.Model")]
    public partial class ComentarioGeneral : object
    {
        
        private int IdComentarioField;
        
        private int IdReporteField;
        
        private ServiceReference1.ReporteTutoria ReporteTutoriaField;
        
        private string descripcionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdComentario
        {
            get
            {
                return this.IdComentarioField;
            }
            set
            {
                this.IdComentarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdReporte
        {
            get
            {
                return this.IdReporteField;
            }
            set
            {
                this.IdReporteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.ReporteTutoria ReporteTutoria
        {
            get
            {
                return this.ReporteTutoriaField;
            }
            set
            {
                this.ReporteTutoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descripcion
        {
            get
            {
                return this.descripcionField;
            }
            set
            {
                this.descripcionField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public partial class Mensaje : object
    {

        private bool errorField;

        private string mensajeField;

        private ServiceReference1.Academico usuarioAutenticadoField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool error
        {
            get
            {
                return this.errorField;
            }
            set
            {
                this.errorField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mensaje
        {
            get
            {
                return this.mensajeField;
            }
            set
            {
                this.mensajeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.Academico usuarioAutenticado
        {
            get
            {
                return this.usuarioAutenticadoField;
            }
            set
            {
                this.usuarioAutenticadoField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName = "ServiceReference1.IService1")]
    public interface IService1
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GuardarAlumno", ReplyAction="http://tempuri.org/IService1/GuardarAlumnoResponse")]
        System.Threading.Tasks.Task<bool> GuardarAlumnoAsync(ServiceReference1.Estudiante estudiante);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GuardarReporteTutoria", ReplyAction="http://tempuri.org/IService1/GuardarReporteTutoriaResponse")]
        System.Threading.Tasks.Task<bool> GuardarReporteTutoriaAsync(ServiceReference1.ReporteTutoria reporteTutoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GuardarProblematica", ReplyAction="http://tempuri.org/IService1/GuardarProblematicaResponse")]
        System.Threading.Tasks.Task<bool> GuardarProblematicaAsync(ServiceReference1.Problematica problematica);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GuardarComentarioGeneral", ReplyAction="http://tempuri.org/IService1/GuardarComentarioGeneralResponse")]
        System.Threading.Tasks.Task<bool> GuardarComentarioGeneralAsync(ServiceReference1.ComentarioGeneral comentarioGeneral);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RegistrarTutorAcademico", ReplyAction="http://tempuri.org/IService1/RegistrarTutorAcademicoResponse")]
        System.Threading.Tasks.Task<bool> RegistrarTutorAcademicoAsync(ServiceReference1.Academico academico);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerAcademicos", ReplyAction="http://tempuri.org/IService1/ObtenerAcademicosResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Academico[]> ObtenerAcademicosAsync(int programaEducativo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerEstudiantes", ReplyAction="http://tempuri.org/IService1/ObtenerEstudiantesResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Estudiante[]> ObtenerEstudiantesAsync(int programaEducativo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface IService1Channel : ServiceReference1.IService1, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ServiceReference1.IService1>, ServiceReference1.IService1
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public Service1Client() : 
                base(Service1Client.GetDefaultBinding(), Service1Client.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IService1.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), Service1Client.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<bool> GuardarAlumnoAsync(ServiceReference1.Estudiante estudiante)
        {
            return base.Channel.GuardarAlumnoAsync(estudiante);
        }
        
        public System.Threading.Tasks.Task<bool> GuardarReporteTutoriaAsync(ServiceReference1.ReporteTutoria reporteTutoria)
        {
            return base.Channel.GuardarReporteTutoriaAsync(reporteTutoria);
        }
        
        public System.Threading.Tasks.Task<bool> GuardarProblematicaAsync(ServiceReference1.Problematica problematica)
        {
            return base.Channel.GuardarProblematicaAsync(problematica);
        }
        
        public System.Threading.Tasks.Task<bool> GuardarComentarioGeneralAsync(ServiceReference1.ComentarioGeneral comentarioGeneral)
        {
            return base.Channel.GuardarComentarioGeneralAsync(comentarioGeneral);
        }
        
        public System.Threading.Tasks.Task<bool> RegistrarTutorAcademicoAsync(ServiceReference1.Academico academico)
        {
            return base.Channel.RegistrarTutorAcademicoAsync(academico);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Academico[]> ObtenerAcademicosAsync(int programaEducativo)
        {
            return base.Channel.ObtenerAcademicosAsync(programaEducativo);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Estudiante[]> ObtenerEstudiantesAsync(int programaEducativo)
        {
            return base.Channel.ObtenerEstudiantesAsync(programaEducativo);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService1))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService1))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:51258/Service1.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return Service1Client.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IService1);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return Service1Client.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IService1);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IService1,
        }
    }
}
